[project]
name = "sound-analysis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "matplotlib==3.10.0",
    "numpy==2.2.1",
    "scipy==1.14.1",
    "sounddevice>=0.5.1",
    "soundfile==0.12.1",
]
